gitops-runtime:
  global:
    codefresh:
      accountId: 664b0549844e846c77185044
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
